### PR TITLE
Routing to different strategies, bailing early on hard failures

### LINKED ISSUE #11: Helper for "maybe-synchronous" strategies
A lot of strategies take a deferred, only to let-flow/chain it and then in many cases either return a synchronous value or synchronously throw an exception.

### LINKED ISSUE #12: Retrying should support predicates on failures
Use cases include:
- When I see a failure that the server is hosed, I want to give up _now_ so I can tell them to restart their broken microservice ASAP
- When I see an authentication error I want to reauth instead and forget that error; it shouldn't be considered a failure of the thing I was really trying to do.

This doesn't require changing the retry logic, but just adding a strategy that knows how to dispatch to other strategies. That means strategies can do this right now, it's just more work.

There should probably also be a dispatcher that knows how to dispatch on the _last_ failure since that's the most common case.

### PR DESCRIPTION
**Pull request by lvh**
Closes #12.

Maybe we should just close #11 too, because honestly all it's saying is that you need help with `(md/chain d ...)` and `(let-flow [...] ...)` and after writing these I'm no longer convinced that's the case.

### CODE REVIEW

**Comment by lvh** [comment]
Feedback sought: naming.

File: src/banach/retry.clj [hunk 1]
```diff
@@ -4,6 +4,39 @@
...
+  [d]
+  (md/chain d (fn [{:keys [failures]}] (throw (last failures)))))
+
+(defn fatal-ctx
+  "Creates a strategy that bails (throws the most recent exception) if the
+  context shows a fatal state (according to the given predicate)."
+  [is-fatal-ctx?]
+  (routing
+   is-fatal-ctx? give-up
+   (constantly true) identity))
```
Comment (lvh) [inline src/banach/retry.clj]: By the way, with this new fn you could write `up-to` as follows:

```clojure
(fatal-ctx #(-> % :failures count (>= n)))
```

... but maybe that isn't necessary :)

File: README.md [hunk 2]
```diff
@@ -5,16 +5,56 @@
...
+    (r/exponentially 2)
+    (r/up-to 5)
+    (r/fatal-exception (fn [e] (= (.getMessage e) "KABOON")))))
+```
+
+(Note that the fatal exception check should probably come last in the `comp`:
+you wouldn't want to potentially back off for some number of seconds for an
+exception you know you'll never recover from anyway.)
+
+Deep down, this functionality is build on a concept called "strategies", which
```
Comment (derwolfe) [inline README.md]: build/built

File: README.md [hunk 3]
```diff
@@ -5,16 +5,56 @@
...
+
+Banach provides flexible tools for doing retries of functions that can fail. By
+default, it offers composable exponential backoff, maximum number of attempts,
+and hard failures (that stop future retry attempts).
+
+Minimum viable snippet (with the `banach.retry` namespace aliased as `r`):
+
+```clojure
+(r/retry f (comp (r/exponentially 2) (r/up-to 5)))
+```
```
Comment (lvh) [inline README.md]: Am I going blind? Did I mess up the backticks? Did GitHub highlighting get really confused and start highlighting the next few paragraphs as Clojure?

**Comment by lvh** [comment]
FYI, I need this behavior, so if this gets merged a release would be very much appreciated.

File: README.md (hunk 3 above)
Comment (derwolfe) [reply README.md]: I think this is just github being silly.

File: README.md [hunk 4]
```diff
@@ -5,16 +5,56 @@
...
+    (r/fatal-exception (fn [e] (= (.getMessage e) "KABOON")))))
+```
+
+(Note that the fatal exception check should probably come last in the `comp`:
+you wouldn't want to potentially back off for some number of seconds for an
+exception you know you'll never recover from anyway.)
+
+Deep down, this functionality is build on a concept called "strategies", which
+take a (potentially deferred) context and return a (potentially deferred)
+context. Because they're deferred, and because the context is a general,
```
Comment (derwolfe) [inline README.md]: > ... take a (potentially deferred) context and return a (potentially deferred) context. Because they're deferred, ...

The way this is worded it makes it seem like the "they" to which you are referring is the context but I think that you mean the strategy is a deferred?

File: README.md [hunk 5]
```diff
@@ -5,16 +5,56 @@
...
+extensible map, this lets you implement pretty much any retry strategy you want
+in a composable way. By default, contexts contain a vector of failures
+(exceptions) encountered so far. So, for example, if you knew that seeing one
+particular exception after another particular exception warranted special
+behavior, you can easily do that, too.
 
+Other fns you may want to check out: `fatal-ctx` (like `fatal-exception` but
```
Comment (derwolfe) [inline README.md]: fns should probably be surrounded in backticks or spelled out as functions.

File: src/banach/retry.clj [hunk 6]
```diff
@@ -4,6 +4,39 @@
    [manifold.deferred :as md]
    [manifold.time :as mt]))
 
+(defn routing
+  "Returns a strategy that routes to different strategies based on context
+  predicates. Kinda like [[cond]], but for strategies."
```
Comment (derwolfe) [inline src/banach/retry.clj]: I am having a bit of trouble understanding "Kinda like [[cond]], but for strategies". Could you explain this a bit more?

File: test/banach/retry_test.clj [hunk 7]
```diff
@@ -5,6 +5,40 @@
             [clojure.math.numeric-tower :as math]
             [banach.retry :as retry]))
 
+(def ctx-1 {:failures [(Exception. "Slow your roll")]})
+(def ctx-2 (update ctx-1 :failures conj (Exception. "KABOOM")))
+
+(deftest routing-tests
+  (let [strat (retry/routing
+               (comp odd? count :failures) identity
+               (constantly true) retry/give-up)]
```
Comment (derwolfe) [inline test/banach/retry_test.clj:14]: I had a bit of trouble understanding this strategy and I'd like to make sure that I am:

1. `(comp odd? count :failures) identity` - if the `context` contains an odd number of failures, return the identity of the `context`, which is the `context` itself. If this fails, then fall through to the next route.
2. `(constantly true) retry/give-up)` if this has been reached, throw the most recently captured exception.

**Review by derwolfe — CHANGES_REQUESTED** [review]
@lvh thanks for this :) I only have a few questions/comments that I'd like to see addressed.

File: README.md (hunk 4 above)
Comment (derwolfe) [reply README.md]: Nope - I misread this :) It is clear as is.

Comment (lvh) [reply README.md]: I'll make the antecedent unambiguous anyway; it does seem likely to trip people up.

File: test/banach/retry_test.clj (hunk 7 above)
Comment (lvh) [reply test/banach/retry_test.clj:14]: Yep, that is correct. Do you feel the most confusing part is:

1. the predicate
2. `identity` as a strategy
3. something else?

**Comment by lvh** [comment]
I think describing `routing` as `cond` does more harm than good, so I just wrote a real docstring.

File: src/banach/retry.clj [hunk 8]
```diff
@@ -4,6 +4,63 @@
...
+  will want a `(constantly true)` clause at the end to implement a default
+  fallback strategy for unforeseen exceptions."
+  [& pred-strat-pairs]
+  (fn [d]
+    (md/chain
+     d
+     (fn [{:keys [failures] :as ctx}]
+       (if-some [strat (first (for [[pred strat] (partition 2 pred-strat-pairs)
+                                    :when (pred ctx)]
+                                strat))]
```
Comment (lvh) [inline src/banach/retry.clj:32]: I would like `seek` in core.

File: src/banach/retry.clj [hunk 9]
```diff
@@ -4,6 +4,63 @@
...
+  [is-fatal-ctx?]
+  (routing
+   is-fatal-ctx? give-up
+   (constantly true) identity))
+
+(defn fatal-exception
+  "Creates a strategy that bails (throws the most recent exception) if it
+  matches the given predicate.
+
+  See also [[fatal-ctx]]; the difference with this function is that this
```
Comment (derwolfe) [inline src/banach/retry.clj:57]: Just as an aside - I think what threw me with `[[cond]]` was the unfamiliar documentation style. Is `[[]]` just used for syntax highlighting function names? (edited through>threw) ☕️

File: test/banach/retry_test.clj (hunk 7 above)
Comment (derwolfe) [reply test/banach/retry_test.clj:14]: I think it may have been the final pair `(constantly true) retry/give-up`. It makes sense when I look at it now, but it was a bit confusing to think that we need to have a bit of special handling to effectively attach an errback at the end of the strategy.

File: src/banach/retry.clj (hunk 9 above)
Comment (lvh) [reply src/banach/retry.clj:57]: Ah. That's codox-speak for linking to a definition, yes.

File: test/banach/retry_test.clj (hunk 7 above)
Comment (lvh) [reply test/banach/retry_test.clj:14]: Do you think specialcasing `:else` would make it worse or better? (`:else` is the preferred fallback clause for cond; although keep in mind that's different, because in cond it works, accidentally, by virtue of being truthy.)

Comment (lvh) [reply test/banach/retry_test.clj:14]: Oh, wait, I see your point. The confusion isn't about fallbacks, it's that `give-up` is your fallback! That's a good point.

**Comment by lvh** [comment]
Oops: just noticed I forgot to comment: I think these are all of the changes, unless you want me to come up with a better test.

**Review by derwolfe — APPROVED** [review]

**Comment by derwolfe** [comment]
Look's great. I'll do a release this evening. Thanks :)
